#' %% LaTeX2e file `R/Rxls-1.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 1.
#' ## ----echo=FALSE,eval=TRUE,results="hide"---------------------------------
we_cpp<-"
// -*- mode: c++; -*-
//#define WIN32_LEAN_AND_MEAN 1
#include <windef.h>
#include <winbase.h>
#include <wingdi.h>
#include <winuser.h>
#undef ERROR
#include <Rcpp.h>
using namespace Rcpp;
//   http://www.rcpp.org/
//   http://adv-r.had.co.nz/Rcpp.html
//   http://gallery.rcpp.org/
//
void* _wnd=NULL;

BOOL CALLBACK EnumWindowsProc(HWND wnd, LPARAM lParam);

BOOL CALLBACK EnumWindowsProc(HWND wnd, LPARAM lParam)
{
  return (_wnd==wnd? FALSE:TRUE);
}
// [[Rcpp::export]]
LogicalVector windowExists(long hwnd)
{
  BOOL ret;
  _wnd = (void*)(hwnd);
  ret = EnumWindows(EnumWindowsProc,0);
  return (ret==FALSE);
}
"
## chunk 2.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
## -*- mode: R; ess-indent-level=2; -*-
## (setq ess-indent-level 2)
opts_chunk$set(tidy.opts=list(width.cutoff=60),
               comment=NA, prompt=TRUE,
               highlight=FALSE,
               self.contained=FALSE)
options(deparse.cutoff=55,width=55)
while("functions:knitall" %in% search()) detach("functions:knitall")
attach(name="functions:knitall",warn.conflict=FALSE,
       what=local({
           unload.pkgs<-function (x) {
               x<-x[paste("package",x,sep=":") %in% search()]
               for(pkg in x) unloadNamespace(pkg)
           }

           getExcelWithRdev<-function(XL=NULL,
                                      new=FALSE,
                                      nonempty=TRUE,
                                      connect=TRUE){
               ##on.exit({rm(XL);gc()})
               XLvalid<-try(comIsValidHandle(XL),silent=TRUE)
               if(inherits(XLvalid,'try-error') ||  (!XLvalid) || !new)
                   XL<-comGetObject("excel.application")
               if(is.null(XL)) XL<-comCreateObject("excel.application")
               if(is.null(XL)) stop("EXCEL not found")
               if(!comIsValidHandle(XL$workbooks("Rdev.xlam"))){
                   rdev<-normalizePath(file.path(Sys.getenv("appdata"),
                                                 "Rxls","Rdev.xlam"),
                                       mustWork=TRUE)
                   XL$workbooks()$open(rdev)
                   Sys.sleep(0.5)
               }
               if(nonempty && (XL$workbooks()$count()==0)){
                   XL$workbooks()$add()
                   Sys.sleep(0.5)
               }
               if(connect) XL$run("R.RIC.connect",TRUE)
               invisible(XL)
           }

           ActiveCellInNewWb<-function(XL=THISXL){
             withObj(XL$workbooks()$add(), .$sheets(1)$range("$A$1")$activate())
             gc()
             invisible(NULL)
           }

           as.XLdata<-function(x,nrow=length (x),ncol=1) {
             if (is.matrix (x)) return (x)
             dim(x)<-c (nrow,ncol)
             x
           }

           fp <- function(...,dot=getwd()) {
             normalizePath(file.path(dot,...),mustWork=FALSE)
           }

           capturewnd<-function(...,.XL=THISXL){
             .hwnd<-.XL$hwnd()
             .fp<-fp("bmp",...)
             gc()
             .XL$run("Rdev.xlam!capturewnd.capturewnd",.hwnd,.fp)
             Sys.sleep(.5)
           }

           setRibbon<-function(XL=THISXL,hide=TRUE,extraKeys=""){
             h1<-XL$activewindow()$height()
             .hwnd<-XL$hwnd()
             keys<-paste("^{F1}",extraKeys,sep="")
             gc()
             XL$run("R.WINAPI.sendkeysToHwnd",.hwnd,keys)
             Sys.sleep(.5)
             h2<-XL$activewindow()$height()
             if(((h1>h2) && hide) || ((h1<h2) && !hide)){
               gc()
               XL$run("R.WINAPI.sendkeysToHwnd",.hwnd,"^{F1}")
             }
           }

           ##           require(Rcpp,quietly = TRUE)
           ##           Rcpp::sourceCpp(code=we_cpp,env=environment())
           ##           we_code<-NULL
           ## this defines windowExists function!
           mknext<-function(iter=function(...){},repr=function(x)x,
                            maxiter=5,init=NULL,
                            wait=.01)
             {
               last<-repr(init)
               function(...){
                 i<-0
                 x<-NULL
                 repeat{
                   i<-i+1
                   x<-iter(...)
                   rx<-repr(x)
                   if((is.null(x) || identical(rx,last)) && i<=maxiter){
                     cat(".");i<<-i+1
                   }else{
                     last<<-rx
                     if(i>maxiter) x<-NULL
                     break()
                   }
                   x<-NULL;gc();gc()
                   Sys.sleep(wait)
                 }
                 return(x)
               }
             }
           closeAllExcel<-function(){
             nextXL<-mknext(iter=function(...)
               withObj(comGetObject("excel.application"),
                       if (comIsValidHandle(.)) {.[["visible"]]<-TRUE;.}),
                            repr=function(x) x[["hwnd"]]
                            )
             repeat{
               if(is.null(THISXL<-nextXL())) break()
               cat("\nexcel[",THISXL[["hwnd"]],"]",sep="")
               THISXL[["displayalerts"]]<-FALSE
               THISXL$quit() ## $
               THISXL<-NULL
               Sys.sleep(.05)
               gc()
               gc()
               Sys.sleep(.05)
             }
             rm (nextXL);gc ();gc();invisible(NULL);
           }

           safe.detach<-function(names){
             for(nn in names)
               while(nn %in% search()) detach(nn,character.only=T)
           }
           change.cmd<-function(cmd,fun,keep,...){
             x<-parse(text=cmd,keep.source = FALSE)
             y<-x[[1]]
             if(!missing(keep)) {
               y<-y[c(1,match(keep,names(y),nomatch = 0))]
               if(!is.null(names(keep))){
                 names(y)<-c("",names(keep))
               }
             }
             if(!missing(fun))  y[[1]]<-as.name(fun)
             z<-list(...)
             if(length(z)>0) y[names(z)]<-z
             x[[1]]<-y
             as.character(x)
           }
           environment()
         }))
unload.pkgs(c("jaradek2013","Rxls","com","comproxy"))
#' % $
#' %% LaTeX2e file `R/Rxls-2.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
#' 
#'   {\ttfamily
#'     \begin{tabular}{rr@{}}\multicolumn{2}{l}{\textbf{Verziószámok}}\\
#'       \Sexpr{with(list(pkgs=c("Rxls","com","comproxy")),
#'       with(list(pkgver=sapply(lapply(pkgs,packageVersion),as.character)),
#'       paste(pkgs,":&" ,pkgver,"\\\\",collapse="\n",sep="")))}
#'     \end{tabular}
#'   }%
#' %% LaTeX2e file `R/Rxls-3.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 3.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
suppressPackageStartupMessages(require(Rxls))
## chunk 4.
## ------------------------------------------------------------------------
comRegisterRegistry()
comCheckRegistry()
#' %% LaTeX2e file `R/Rxls-4.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 5.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
suppressWarnings(closeAllExcel())
unloadNamespace("Rxls")
unloadNamespace("com")
unloadNamespace("comproxy")
unlink(file.path(Sys.getenv("appdata"),"Rxls"),recursive=T)
##rm(list=ls(all=T))
## chunk 6.
## ------------------------------------------------------------------------
require(Rxls)
installRxls()
#' %% LaTeX2e file `R/Rxls-5.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 7.
#' ## ------------------------------------------------------------------------
Sys.getenv("appdata")
#' %% LaTeX2e file `R/Rxls-6.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 8.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
suppressPackageStartupMessages({require(com);require(Rxls)})
getExcelWithRdev(NULL)
cmd<-withObj(THISXL,{
                 ##if(.$workbooks()$count()==0)
                 ## .$workbooks()$add()
                 ##.$run("R.RIC.connect",TRUE)
                 ## Sys.sleep(.1)
                 cmd<-.$run("R.RIC.defaultcmd")
                 cmd2<-change.cmd(cmd,fun="ls.str",
                                  keep=c("envir"="env"),all.names=TRUE)
                 cmd1<-sub("[$]wb_[^,]*," , "," , cmd2)
                 cmd3<-"ls.str(2,all=TRUE)"
                 cmd4<-"search()[1:5]"
                 ##cmd5<-"THISXL"
                 paste(cmd1,cmd2,cmd3,cmd4,##cmd5,
                       sep="\n")
             })

## acmd<-change.cmd(cmd,
##            fun="with",
##            keep=c(env="envir"),
##            expr=substitute(attach(list(THISXL=THISXL,
##            .wbname=.wbname,.wsname=.wsname),
##            name="XL")))

#xlins<-ls(all=T,pattern="^.XL",envir=.GlobalEnv)
#assign(xlins,get(xlins,.GlobalEnv))
#rm(xlins)
## chunk 9.
## ----code=cmd------------------------------------------------------------
## chunk 10.
#' ## ----echo=FALSE,results="hide",eval=FALSE--------------------------------
safe.detach("XL")
local({
    cmd<-change.cmd(cmd,fun="eval",
                    keep=c(expr="envir"),
                    env=substitute(.GlobalEnv))
    xlenv<-eval(parse(text=cmd))
    attach(with(xlenv,list(THISXL=THISXL)),name="XL")
})
##rm(list=ls(all=TRUE))
#' %% LaTeX2e file `R/Rxls-7.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 11.
#' ## ----hibas---------------------------------------------------------------
wb<-THISXL[["workbooks"]]$add()
cell<-wb[["sheets",1]][["range","$A$1"]]
cell[["value"]]
cell[["value"]]<-1
cell[["value"]]
cell<-cell$offset(1,0)
cell[["formula"]]<-"=$A$1+2"
cell[["formula"]]
cell[["value"]]
cell<-NULL
#' %% LaTeX2e file `R/Rxls-8.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 12.
#' ## ------------------------------------------------------------------------
df <- data.frame(Dátum = seq.Date(as.Date("2012-01-01"),
by = "1 month", length = 5))
df$díj <- rnorm(nrow(df), 100)
df$kárkifizetés <- rnorm(nrow(df), 70)
df
XLwritedf(XLrange = THISXL[["range", "$C$1"]], df = df,
with.names = TRUE, autoFit = TRUE, setname = "havi_bontás")
#' %% LaTeX2e file `R/Rxls-9.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 13.
#' ## ------------------------------------------------------------------------
## wb a korábban létrehozott új munkafüzet
address<-wb[["names"]]$item("havi_bontás")[["refersto"]] #$
address
df1<-XLreaddf.cols(address)
df1
## vagy
range<-wb[["names"]]$item("havi_bontás")[["referstorange"]]
range$address(external=TRUE)
df2<-XLreaddf.cols(XLrange=range)
identical(df1,df2)
## chunk 14.
## ----echo=FALSE,results="hide"-------------------------------------------
range<-NULL
wb$close(FALSE)
wb<-NULL
rm(range,wb,address,cell)
gc()
#' %% LaTeX2e file `R/Rxls-10.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 15.
#' ## ------------------------------------------------------------------------
XLDate(df1$Dátum)
## chunk 16.
## ----echo=FALSE,results="hide"-------------------------------------------
rm(df,df1,df2)
#' %% LaTeX2e file `R/Rxls-11.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 17.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
msg<-function(...) {
  cat("\n",sprintf(...),"\n",sep="");
  flush.console()
}

getExcelWithRdev(NULL,new=TRUE)

msg("XL ribbon visible")
withObj(THISXL,{
  Sys.sleep(2)
  .[["visible"]]<-TRUE;
  .[["top"]]<-0;
  .[["left"]]<-0
  .[["height"]]<-190
  .$range("$A$1")$select()
})
setRibbon(THISXL,hide=TRUE)
setRibbon(THISXL,hide=FALSE,extraKeys="%y{ESCAPE}{ESCAPE}")
##{ESCAPE}{ESCAPE}")
capturewnd("Rxls_development_menu.bmp")
setRibbon(THISXL,hide=TRUE)

msg("XL 'newskeleton'")
THISXL$run("Rdev.xlam!newskeleton") #,fp("Calc1"))
Sys.sleep(2)
wb<-THISXL$activeworkbook();

withObj(wb$activesheet(),{
  msg("XL 'Adatok' worksheet")
  withObj(.$range("B5:B7"),{
    .$select()
    THISXL$run ("Rdev.xlam!insertDataLine");
    Sys.sleep(.5)

    .[["value"]]<-as.XLdata(list("Technikai kamat","Nem","Eredmény helye"))
  })
  withObj(.$range ("A5:A7"),
  .[["value"]]<-as.XLdata(list ("i","nem","wsname"))
  )

  withObj(.$range ("C6"),{
    .[["value"]]<-"férfi;női"
    .$select ()
  })
  THISXL$run ("Rdev.xlam!insertDropDown");
  Sys.sleep(.5)

  withObj(.$range("E5:E6"),
  .[["value"]]<-as.XLdata(list(0.05,"férfi")))

  withObj(.$range("E7"),
  .[["formula"]]<-'="Komm. számok ("&D6&",i="&D5&")"')

  .$range ("C6")$select ()
})

msg("XL 'adatok.bmp'")
withObj(THISXL,{
  .[["height"]]<-245
  .[["width"]]<-680
})
capturewnd("adatok.bmp")

local({
  cmd<-THISXL$activesheet()$shapes(1)$onaction()
  Sys.sleep(.1)
  suppressMessages(THISXL$run(cmd,TRUE))
  Sys.sleep(.1)
})

msg("XL inserting lx")
lx2003<-read.csv("lx2003.txt",sep=";")

withObj(wb$worksheets()$add(),{
  .[["name"]]<-"lx"
  XLwritedf(XLrange=.$range("A1"),df=lx2003)
  wb$names()$add(name="lxdata",refersto=.$usedrange())
})

withObj(wb$worksheets("R kód"),{
  .$activate()
  .$names("R_data")$referstorange ()$select()
})

withObj(THISXL,{
  .[["height"]]<-170
  r<-.$selection()
  withObj(.$activewindow(),{
    .[["scrollcolumn"]]<-r$columns(1)$column()
    .[["scrollrow"]]<-r$rows(1)$row()
  })
})
capturewnd("R-kod.bmp")
#' %% LaTeX2e file `R/Rxls-12.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 18.
#' ## ------------------------------------------------------------------------
cat(readLines("calc.R"), sep = "\n")
#' %% LaTeX2e file `R/Rxls-13.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 19.
#' ## ------------------------------------------------------------------------
source("calc.R", local = TRUE)
str(cn)
#' %% LaTeX2e file `R/Rxls-14.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 20.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
cmd<-local({
  cmd<-THISXL$run("R.RIC.defaultcmd")
  Sys.sleep(.1)
  change.cmd(cmd,fun="ls.str",keep="env",all.names=TRUE)
})
## chunk 21.
## ----code=cmd------------------------------------------------------------
#' % XLid<-ls(pos=1,pattern="\\.XL[0-9]+",all=T)
#' % XLid
#' % ls.str(XLenv<-get (XLid,pos=1))
#' % wbid<-ls(envir=XLenv,pattern="wb_Calc")
#' % ls.str(get(wbid,envir=XLenv))
#' %% LaTeX2e file `R/Rxls-15.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 22.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
writeLines(readLines("../aux/calc1.R",encoding="UTF-8"),sep="\n",con="calc1.R")
## chunk 23.
## ------------------------------------------------------------------------
calc.R <- readLines("calc.R")
calc1.R <- readLines("calc1.R")
cat("új sorok:", setdiff(calc1.R, calc.R), "\ra régi helyett:",
                 setdiff(calc.R, calc1.R), sep = "\n")
#' %% LaTeX2e file `R/Rxls-16.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 24.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
withObj(wb$worksheets("R kód")$names("R_calc")$referstorange ()$offset (0,3),
.[["value"]]<-"calc1.R")

THISXL$run("Rdev.xlam!insertRcode",fp("calc1.R"),wb)
Sys.sleep(.5)

withObj(THISXL,{
  .[["height"]]<-220
  capturewnd("R-kod_calc1R.bmp")

  .[["height"]]<-295
  withObj(wb$worksheets("R kód"),{
    .$activate()
    .$names("R_calc")$referstorange()$select()
  })
  withObj(.$activewindow(),{
    .[["scrollrow"]]<-2;
    .[["scrollcolumn"]]<-4;
    .[["splitcolumn"]]<-4
    .[["splitrow"]]<-9
    withObj(.$panes(2), .[["scrollcolumn"]]<-9)
    withObj(.$panes(3),.[["scrollrow"]]<-28)
    capturewnd("R-kod-filled.bmp")
    .[["split"]]<-FALSE
  })
})

rm(list=ls(all=T))
gc()
#' 
#' %% LaTeX2e file `R/Rxls-17.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 25.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
if(exists("lekerdezes1.SQL")){
    ## kód az SQL ághoz
}else{
    ## kód az ACCESS ághoz
}
#'     
#' %% LaTeX2e file `R/Rxls-18.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 26.
#' ## ------------------------------------------------------------------------
getFromDB
#'     
#' %% LaTeX2e file `R/Rxls-19.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 27.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
getExcelWithRdev()
withObj(THISXL,.[["visible"]]<-TRUE)
ActiveCellInNewWb()
THISXL$run("R.RIC.connect",TRUE)
## chunk 28.
## ------------------------------------------------------------------------
x<-seq.Date(as.Date ("2013-01-01"),as.Date ("2014-01-1"),by="1 month")
df<-data.frame(date=x)
XLwritedf(df=df,setname="datumok")
df["R->EXCEL->R.date"]<-XLreaddf.cols("datumok",value="value")
df["eltérés"]<-with(df,as.POSIXct(as.POSIXlt(date),tz="CET")-`R->EXCEL->R.date`)
df["eltérés2"]<-with(df,date-as.Date(`R->EXCEL->R.date`,tz=""))
df[with (df,`eltérés`!=0 | `eltérés2`!=0),,drop=FALSE]
#'   
#' %% LaTeX2e file `R/Rxls-20.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 29.
#' ## ------------------------------------------------------------------------
x1<-XLget("datumok")[2:14,1]
x1<-Rxls:::unlist.keepclass(x1)
x2<-XLget(XLrange=THISXL$range("datumok")$range("A2:A14"))
x2<-Rxls:::unlist.keepclass(x2)
df<-data.frame("név cellával"=x1,
               "név cella nélkül"= x2, "eltérés"=x1-x2,
               check.names=FALSE)
df[with(df,`eltérés`!=0),]
#'   
#' %% LaTeX2e file `R/Rxls-21.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 30.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
turnOn <- XLScreenUpdateTurnOff(Appl = THISXL)
on.exit(turnOn(), add = TRUE)
#' %% LaTeX2e file `R/Rxls-22.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 31.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
THISXL$range("$A:$A")$value()
#'   
#' %% LaTeX2e file `R/Rxls-23.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 32.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
detachXL<-attachXL(env)
on.exit(detachXL(),add=TRUE)
#'   
#' %% LaTeX2e file `R/Rxls-24.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 33.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
txt<-c("print('Ez egy üzenet EXCELből');",
       "withObj(THISXL[['activecell']][['offset',1]],.[['value']]<-'Ez meg a válasz')")
THISXL
wb<-THISXL$workbooks()$add()
wb$activate()
THISXL$range("$A$1")$activate()
withObj(THISXL$activecell(),{
            .[["value"]]<-paste(txt,collapse=" ")
            .[["wraptext"]]<-FALSE
            .$entirecolumn()$autofit()
        })
THISXL$run("Rdev.xlam!insertform.insertcalcbtn",", short:=True")
Sys.sleep(.5)
cmd<-THISXL$activesheet()$shapes(1)$onaction()
Sys.sleep(.5)
suppressMessages(THISXL$run(cmd))
Sys.sleep(.5)
withObj(THISXL,.[["height"]]<-130)
capturewnd("FUN_result.bmp")
wb<-NULL
gc()
cmd<-change.cmd(THISXL$run("R.RIC.defaultcmd"),
                fun="with",
                keep=c(data="env"),
                expr=substitute (.FUN))
                                        #$
## chunk 34.
#' ## ----echo=FALSE----------------------------------------------------------
cat(paste(txt,collapse="\n"))
#' %% LaTeX2e file `R/Rxls-25.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 35.
#' ## ----code=cmd------------------------------------------------------------
#' %% LaTeX2e file `R/Rxls-26.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 36.
#' ## ------------------------------------------------------------------------
XLwith
#' %% LaTeX2e file `R/Rxls-27.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 37.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
data <- read.access()
res <- do.calc(data)
save.results(res)
#' %% LaTeX2e file `R/Rxls-28.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 38.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
pb <- progress("%s...", "")
pb$step("ACCESS adatbázis olvasása")
data <- read.access()
pb$step("Számolás")
res <- do.calc(data)
pb$step("Eredmények mentése")
save.results(res)
pb$rm()
rm(pb)
#' %% LaTeX2e file `R/Rxls-29.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 39.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
do.calc <- function(x) {
    pb <- progress(sprintf(" [%%d/%d]", length(x)), 0, lazyness = 0.3)
    on.exit({
        pb$refresh()
        pb$rm()
    })
    sapply(x, function(y) {
               pb$inc()
               ## egy számolási lépés y-on
           })
}
#' %% LaTeX2e file `R/Rxls-30.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 40.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
withObj(THISXL,{
  .[["height"]]<-350
  setRibbon(.,hide=TRUE)
  withObj(.$workbooks("Rdev.xlam"),{
    .[["isaddin"]]<-FALSE
    .$names("path")$referstorange()$select()
    capturewnd("samples.bmp")
    .[["isaddin"]]<-TRUE
  })
})

#' %% LaTeX2e file `R/Rxls-31.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 41.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
suppressMessages(require(formatR))
showfundef<-function (x,...){
  name<-deparse(substitute(x))
  body(x)<-NULL;
  y<-capture.output(.Internal(print.function(x,TRUE,...)));
  cat(y[-(length(y)-0:1)],sep="\n");
  invisible(unclass(x))
}
## chunk 42.
## ----prompt=FALSE,render=showfundef--------------------------------------
XLdata
#' %% LaTeX2e file `R/Rxls-32.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 43.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLsource
#' %% LaTeX2e file `R/Rxls-33.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 44.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLwritedf
#' %% LaTeX2e file `R/Rxls-34.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 45.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLreaddf.cols
XLreaddf.rows
#' %% LaTeX2e file `R/Rxls-35.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
#' 
#' %<<echo=FALSE,results="hide">>=
#' %XLlist2df<-Rxls:::XLlist2df;class (XLlist2df)<-"fundef"
#' %@
## chunk 46.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
Rxls:::XLlist2df
#'   
#' %% LaTeX2e file `R/Rxls-36.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 47.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLget
#' %% LaTeX2e file `R/Rxls-37.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 48.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
ACCESS.get
#' %% LaTeX2e file `R/Rxls-38.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 49.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
ODBC.get
#' %% LaTeX2e file `R/Rxls-39.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 50.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
##if(exists("getFromDB")) rm(getFromDB)
## chunk 51.
## ----prompt=FALSE,render=showfundef--------------------------------------
getFromDB
#' %% LaTeX2e file `R/Rxls-40.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 52.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
logDev
logDev.set
#' %% LaTeX2e file `R/Rxls-41.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 53.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
progress
#' %% LaTeX2e file `R/Rxls-42.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 54.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
logMessage
#' %% LaTeX2e file `R/Rxls-43.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 55.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLDate
XLPOSIXct
#' %% LaTeX2e file `R/Rxls-44.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 56.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLScreenUpdateTurnOff
#' %% LaTeX2e file `R/Rxls-45.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 57.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
XLusedrange
#' %% LaTeX2e file `R/Rxls-46.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 58.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
pkgzip
#' %% LaTeX2e file `R/Rxls-47.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 59.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
installRxls
#' %% LaTeX2e file `R/Rxls-48.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 60.
#' ## ----prompt=FALSE,render=showfundef--------------------------------------
R_RegEntries
#' %% LaTeX2e file `R/Rxls-49.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 61.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
fns<-ls()
rm(list=fns[sapply(sapply(fns,get,envir=environment()),inherits,"fundef")])
rm (fns)
#' %% LaTeX2e file `R/Rxls-50.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 62.
#' ## ------------------------------------------------------------------------
THISXL[["workbooks"]]
THISXL$workbooks()
#' %$
#' %% LaTeX2e file `R/Rxls-51.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 63.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
THISXL[["workbooks", 1]]
THISXL[["workbooks"]][["item", 1]]
THISXL$workbooks(1)
THISXL$workbooks()$item(1)
THISXL[["workbooks"]]$item(1)
THISXL$workbooks()[["item", 1]]
#' %$
#' %% LaTeX2e file `R/Rxls-52.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 64.
#' ## ------------------------------------------------------------------------
wb <- THISXL$workbooks()$add()
#' %% LaTeX2e file `R/Rxls-53.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 65.
#' ## ------------------------------------------------------------------------
withObj(THISXL,.[["activecell"]]<-1)
withObj(THISXL[["activecell"]],.[["value"]]<-1)
THISXL[["activecell"]] <- 1
THISXL[["activecell"]][["value"]] <- 1
ac <- THISXL$activecell()
ac[["value"]] <- 1
ac <- NULL
#' %$
#' %% LaTeX2e file `R/Rxls-54.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 66.
#' ## ------------------------------------------------------------------------
wb$close(FALSE)
wb <- NULL
gc()
#' %$
#' %% LaTeX2e file `R/Rxls-55.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 67.
#' ## ----eval=FALSE,prompt=FALSE---------------------------------------------
f <- function() {
  wb <- THISXL$workbooks()$add()
  on.exit(wb$close(FALSE), add = TRUE)
  ## ...
}
#' %$
#' %% LaTeX2e file `R/Rxls-56.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 68.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
ws<-THISXL[["activeworkbook"]][["sheets"]]$add()
ws$range("A1")$activate() ## $
rm(ws)
gc ()
## chunk 69.
## ------------------------------------------------------------------------
THISXL[["activecell"]][["formula"]] <- "=MA()"
#' %% LaTeX2e file `R/Rxls-57.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 70.
#' ## ------------------------------------------------------------------------
THISXL[["activecell"]][["formula"]]
XLDate(THISXL[["activecell"]][["value2"]])
#' %% LaTeX2e file `R/Rxls-58.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 71.
#' ## ------------------------------------------------------------------------
withObj(THISXL[["activecell"]], .[["formula"]] <- "=MA()")
THISXL[["activecell"]][["formula"]]
XLDate(THISXL[["activecell"]][["value2"]])
#' %% LaTeX2e file `R/Rxls-59.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 72.
#' ## ------------------------------------------------------------------------
`[[.COMObject` <- function(handle, property, ...) {
  print(match.call())
  cat("\thandle =", deparse(handle), "\n")
  x <- com::`[[.COMObject`(handle, property, ...)
  cat("\treturn value =", deparse(x), "\n\n")
  x
}
`[[<-.COMObject` <- function(handle, property, ...) {
  print(match.call())
  cat("\thandle =", deparse(handle), "\n")
  x <- com::`[[<-.COMObject`(handle, property, ...)
  cat("\treturn value =", deparse(x), "\n\n")
  x
}
THISXL[["activecell"]][["formula"]] <- "=MA()"
#' %% LaTeX2e file `R/Rxls-60.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 73.
#' ## ----eval=FALSE----------------------------------------------------------
vignette("Rxls")
#' %% LaTeX2e file `R/Rxls-61.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 74.
#' ## ----echo=FALSE,result='hide'--------------------------------------------
if(exists("THISXL",inherits=FALSE)) rm (THISXL)
#' %% LaTeX2e file `R/Rxls-62.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 75.
#' ## ----eval=FALSE----------------------------------------------------------
options(pkgType = "both")
#' %% LaTeX2e file `R/Rxls-63.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 76.
#' ## ----eval=FALSE----------------------------------------------------------
install.packages("<csomag elérési útja>", type = "source", repos = NULL)
#' %% LaTeX2e file `R/Rxls-64.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 77.
#' ## ----eval=FALSE----------------------------------------------------------
install.packages("<com tar.gz elérési útja>", type = "source", repos = NULL, INSTALL_opts = "--no-multiarch")
#' %% LaTeX2e file `R/Rxls-65.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 78.
#' ## ----eval=FALSE----------------------------------------------------------
install.packages("<com tar.gz elérési útja>", type = "source", repos = NULL)
#' %% LaTeX2e file `R/Rxls-66.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 79.
#' ## ----eval=FALSE----------------------------------------------------------
comRegisterRegistry()
#' %% LaTeX2e file `R/Rxls-67.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 80.
#' ## ------------------------------------------------------------------------
comCheckRegistry()
#' %% LaTeX2e file `R/Rxls-68.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 81.
#' ## ----prompt=FALSE,message=FALSE,warning=FALSE,tidy=FALSE-----------------
require(inline)
require(Rcpp)
funs<-c("LENGTH","Rf_length")
names(funs)<-paste("test",funs,sep="_")
body.pat<-'
  SEXP sexp = R_NilValue;
  sexp = R_MakeExternalPtr(NULL,R_NilValue,R_NilValue);
  return IntegerVector::create( _["%s"]=%s(sexp));
'

body<-lapply(funs,function(x)sprintf(body.pat,x,x))

test<-cxxfunction(sig=lapply(funs,"[",0), body=body, plugin="Rcpp")
names(test)<-funs

for(x in names(test)){
  cat(sprintf("Running 'test$%s':\n result: ",x))
  cat(eval(substitute(try(test[[x]](),silent=T),list(x=x))))
}
#' %% LaTeX2e file `R/Rxls-69.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 82.
#' ## ----echo=FALSE,results="hide"-------------------------------------------
require(utils)
require(tools)
pkgs<-c("com","comproxy","Rxls","jaradek2013")
pkgsdir<-file_path_as_absolute("../pkgs")
Rfilesdir<-file_path_as_absolute("../Rfiles")

unlink(x=dir(pkgsdir,full.names=TRUE))
x<-download.packages(pkgs,
contriburl="file://vboxsrv/prokaj/Rlib/Repository/src/contrib/",type="source")
file.copy(x[,2],pkgsdir)
pkgzip(pkgs,zip.mappa=pkgsdir,ask=FALSE)
## chunk 83.
## ----echo=FALSE----------------------------------------------------------
cat ("A 'pkgs' könyvtár tartalma:",
paste(dir(pkgsdir),
collapse="\n   "),sep="\n   ")
## chunk 84.
## ----echo=FALSE----------------------------------------------------------
cat ("A 'Rfiles' könyvtár tartalma:",
paste(dir(Rfilesdir),
collapse="\n   "),sep="\n   ")
#' %% LaTeX2e file `R/Rxls-70.Rnw'
#' %% generated by the `Rnw' environment
#' %% from source `Rxls' on 2015/09/05.
#' %%
## chunk 85.
#' ## ----echo=FALSE,results='hide'-------------------------------------------
closeAllExcel()
safe.detach(c("functions:knitall","XL"))
XLs<-ls(pattern="\\.XL[0-9]+",pos=1,all.names=TRUE)
if(length(XLs)>0) rm(list=XLs,pos=1)
rm(list=ls(all=T))
gc()
gc()
